services:
  - type: web
    name: blog-platform
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Praveena:praveena1praveena@cluster0.apiyfyh.mongodb.net/blogplatform
      - key: JWT_SECRET
        value: blogspace_secret_key_2026
      - key: PORT
        value: 5000
